version: "3.8"

services:
  server:
    build: ./Server
    container_name: kebele_server
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./Server:/app
    depends_on:
      - db

  client:
    build: ./Client
    container_name: kebele_client
    ports:
      - "3000:3000"
    depends_on:
      - server

  db:
    image: postgres:15
    container_name: kebele_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: kebele_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
